version: "3.8"

services:
  web1:
    image: nginx:alpine
    container_name: nginx-web1
    ports:
      - 8080:80

  web2:
    image: httpd
    container_name: httpd-web2
    ports:
      - 8081:80

  web3:
    image: httpd
    container_name: httpd-web3
    ports:
      - 8082:80
