version: "3.8"

services:
  web1:
    image: nginx:alpine
    container_name: nginx-web1
    ports:
      - 8080:80
    networks:
      - net-test1

  web2:
    image: httpd
    container_name: httpd-web2
    ports:
      - 8081:80
    networks:
      - net-test1
      - net-test2

  web3:
    image: httpd
    container_name: httpd-web3
    ports:
      - 8082:80
    networks:
      - net-test2

networks:
  net-test1:
  net-test2:
